### ISSUE TITLE
로또 구매 기능을 구현한다

### ISSUE THREAD

**Issue by viiviii** [viiviii/jubilant-train#3]
### 구현할 기능

**정상**
- [x] 로그인 페이지로 이동한다
- [x] 계정으로 로그인한다
- [x] 로또 구매 페이지로 이동한다
- [x] 옵션을 선택한다 (자동, 수량)
- [x] 로또를 구매한다

**예외**
- [x] 로그인이 실패하면 예외를 던진다
- [x] 로또 구매에 실패하면 예외를 던진다

### 메모

- 로또 구매 시 다른 url을 사용하는 이유
  -  로또 구매를 누르면 팝업으로 열리는데 위 url을 사용하면 스위칭 없이 구매하기로 갈 수 있음
  - 개발자도구로 보면 구매하기 영역인 iframe에 해당 url이 적혀있다
<img width="654" alt="image" src="https://user-images.githubusercontent.com/75404713/215735213-bceea20d-c05a-4036-b337-d458bb8d7f75.png">

### TODO

- 아이디, 비밀번호 저장 어디에?
- 테스트 격리
- 메서드명에 로또 붙일거면 붙이고 뗄거면 떼라
- 해당 url에 있는지 체크하는 중복 코드
